### ISSUE TITLE
Parameter_bridge does not work

### ISSUE THREAD

**Issue by rows-of-houses** [gazebosim/ros_gz#365] opened 2023-02-21 08:33 UTC
## Environment
* Ubuntu 22.04
* ROS2 Humble
* Gazebo Garden
* caguero/humble_garden branch (I cannot use ros2 branch instead because it crushes while being built)

## Description
* Expected behavior: There is a IMU data in corresponding ROS2 topic
* Actual behavior: Topic, that is created by bridge, is empty

## Steps to reproduce

First terminal
1. `gz sim world.sdf`
2. Run simulation

Second terminal
1. `cd <bridge_workspace>`
2. `. install/setup.bash`
3.   `ros2 run ros_gz_bridge parameter_bridge /imu/data_raw@sensor_msgs/msg/Imu[gz.msgs.IMU`

Third terminal
1. `cd <bridge_workspace>`
2. `. install/setup.bash`
3. `ros2 topic echo /imu/data_raw`

## Output
/imu/data_raw  topic is empty

**Comment by mjcarroll** [comment] 2023-02-22 01:48
Can you try using the `humble` branch, which is recommended for that combination.

https://github.com/gazebosim/ros_gz/blob/e7660f83be0447fe44c1240df2c6468364d2fd24/README.md?plain=1#L10

**Comment by YDenker** [comment] 2023-02-22 09:40
I have an issue with one of my parameter bridges as well that worked just fine before the renaming. All others work just fine.
The bridge that is not working for me is the following:
ros2 run ros_gz_bridge parameter_bridge /collision_detection@ros_ign_interfaces/msg/Contacts[ignition.msgs.Contacts
I am using

Ubuntu 22.04.2 LTS
ROS2 Humble 
Gazebo Citadel

I get the warning that the bridge is not being created:
[WARN] [1677058258.983101520] [ros_gz_bridge]: Failed to create a bridge for topic [/collision_detection] with ROS2 type [/collision_detection] to topic [ros_ign_interfaces/msg/Contacts] with Gazebo Transport type [ignition.msgs.Contacts]

Did something change with the transport types that i am unaware of?

**Comment by rows-of-houses** [comment] 2023-02-24 11:50
I tried using `humble` branch, but it also didn't work.
After 
`ros2 run ros_gz_bridge parameter_bridge /imu/data_raw@sensor_msgs/msg/Imu[gz.msgs.IMU`
 I got
`[INFO] [1677239017.350256340] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/imu/data_raw (gz.msgs.IMU) -> /imu/data_raw (sensor_msgs/msg/Imu)] (Lazy 0)`, 
but there is still no messages in `/imu/data_raw` ROS2 topic. But I see messages in Gazebo topic.

**Comment by rows-of-houses** [comment] 2023-02-28 11:01
I tried to run `imu.launch.py` from demos of `humble` branch. If I launch it without any changes, everything works nice, but Gazebo 6 is launched (I need Gazebo 7). 
In the console output there are lines:
```
[parameter_bridge-2] [INFO] [1677577587.087082303] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/imu (gz.msgs.IMU) -> /imu (sensor_msgs/msg/Imu)] (Lazy 0)
[parameter_bridge-2] [INFO] [1677577587.093286646] [ros_gz_bridge]: Creating ROS->GZ Bridge: [/imu (sensor_msgs/msg/Imu) -> /imu (gz.msgs.IMU)] (Lazy 0)
```
Are these messages correct? I think there should be msg types of ignition.
 
I added next strings to `gz_sim.launch.py` (which is referred by launch file of IMU):
```
print(env)
print(gz_args)
print(gz_version)
print(ign_args)
print(ign_version)
print(debugger)
```
Output is:
```
{'GZ_SIM_SYSTEM_PLUGIN_PATH': 
':/home/username/humble_gz_ws/install/ros_ign_interfaces/lib:
/home/username/humble_gz_ws/install/ros_gz_sim/lib:
/home/username/humble_gz_ws/install/ros_gz_bridge/lib:
/home/username/humble_gz_ws/install/ros_gz_interfaces/lib:
/opt/ros/humble/opt/rviz_ogre_vendor/lib:
/opt/ros/humble/lib/x86_64-linux-gnu
:/opt/ros/humble/lib',

 'IGN_GAZEBO_SYSTEM_PLUGIN_PATH': 
 ':/home/username/humble_gz_ws/install/ros_ign_interfaces/lib
 :/home/username/humble_gz_ws/install/ros_gz_sim/lib:
 /home/username/humble_gz_ws/install/ros_gz_bridge/lib:
 /home/username/humble_gz_ws/install/ros_gz_interfaces/lib:
 /opt/ros/humble/opt/rviz_ogre_vendor/lib:
 /opt/ros/humble/lib/x86_64-linux-gnu:
 /opt/ros/humble/lib'}

-r sensors.sdf
6


false
```
If I try to specify `gz_version` in launch arguments of `imu.launch.py`:
```
gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(pkg_ros_gz_sim, 'launch', 'gz_sim.launch.py')),
        launch_arguments={
            'gz_args': '-r sensors.sdf', 'gz_version': '7'
        }.items(),
    )
```
and launch the IMU launch file, it actually launches Gazebo 7, but there is no messages in ROS2 topic `/imu`. Console output:
```
[INFO] [launch]: All log files can be found below /home/username/.ros/log/2023-02-28-13-15-21-757298-username-pc-68226
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ruby $(which gz) sim-1]: process started with pid [68228]
[INFO] [parameter_bridge-2]: process started with pid [68230]
[INFO] [rqt_topic-3]: process started with pid [68233]
[parameter_bridge-2] [INFO] [1677579322.213397669] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/imu (gz.msgs.IMU) -> /imu (sensor_msgs/msg/Imu)] (Lazy 0)
[parameter_bridge-2] [INFO] [1677579322.220332381] [ros_gz_bridge]: Creating ROS->GZ Bridge: [/imu (sensor_msgs/msg/Imu) -> /imu (gz.msgs.IMU)] (Lazy 0)
[ruby $(which gz) sim-1] 
[ruby $(which gz) sim-1] Using deprecated environment variable [IGN_GAZEBO_RESOURCE_PATH].
[ruby $(which gz) sim-1] Please use [GZ_SIM_RESOURCE_PATH] instead.
[ruby $(which gz) sim-1] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[ruby $(which gz) sim-1] Warning [Utils.cc:130] [/sdf/world[@name="sensors"]/model[@name="force_torque_demo"]/link[@name="base_plate"]/static:/usr/share/gz/gz-sim7/worlds/sensors.sdf:L209]: XML Element[static], child of element[link], not defined in SDF. Copying[static] as children of [link].
[ruby $(which gz) sim-1] Warning [Utils.cc:130] [/sdf/model[@name="force_torque_demo"]/link[@name="base_plate"]/static:<data-string>:L3]: XML Element[static], child of element[link], not defined in SDF. Copying[static] as children of [link].
[ruby $(which gz) sim-1] Warning [Utils.cc:130] [/sdf/model[@name="force_torque_demo"]/link[@name="base_plate"]/static:<data-string>:L3]: XML Element[static], child of element[link], not defined in SDF. Copying[static] as children of [link].
```
There is also `/lidar/points` topic, but I don't know what has spawned it. 
![image](https://user-images.githubusercontent.com/117982412/221825557-851dd685-23ef-4843-a6f3-9cc7b1188cbc.png)

I added new enviromental variable:
`export GZ_SIM_RESOURCE_PATH=/home/username/humble_gz_ws/install/ros_gz_sim_demos/share`
but it didn't help.

UPD: I noticed that in files 
`/home/username/humble_gz_ws/install/ros_gz_sim_demos/share/ament_index/resource_index/parent_prefix_path/ros_gz_sim_demos`,
` /home/username/humble_gz_ws/install/ros_gz_sim_demos/share/ament_index/resource_index/package_run_dependencies/ros_gz_sim_demos` and
`/home/username/humble_gz_ws/install/ros_gz_sim_demos/share/colcon-core/packages/ros_gz_sim_demos`
only `ignition-gazebo6` package mentioned, but there is no any package referred to Gazebo 7. Is it crucial problem? How can I solve it? By the way, `rosdep install -i --from-path src --rosdistro humble -y` shows that All required rosdeps installed successfully.

**Comment by azeey** [comment] 2023-02-28 21:05
I would suggest using the `humble` branch since the `caguery/humble_garden` branch is quite outdated now (https://github.com/gazebosim/ros_gz/compare/caguero/humble_garden..humble). If your build crashes, it's probably due to insufficient memory and following the suggestion in https://github.com/gazebosim/ros_gz/issues/235#issuecomment-1093124301 might help

**Comment by doppioandante** [comment] 2023-03-07 19:43
I am having the same problem, using the `humble` branch, the bridge seems to actually make the topics visible from either side but no message is being delivered, I'm trying the standard chatter message.
Btw the doc is outdated and uses ignition message types

**Comment by doppioandante** [comment] 2023-03-08 21:59
This is a reproducible Dockerfile with the configuration and build steps I'm using:
```Dockerfile
FROM osrf/ros:humble-desktop

RUN apt-get update
RUN apt-get install kakoune wget gnupg apt-utils -y
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update

RUN apt-get install gz-sim7-cli libgz-transport12-dev libgz-math7-dev libgz-cmake3-dev libignition-cmake2-dev -y

RUN useradd --create-home --shell /bin/bash ros2

USER ros2
WORKDIR /home/ros2
RUN rosdep update
RUN mkdir -p /home/ros2/ws/src/
RUN cd /home/ros2/ws/src/ && git clone --depth 1 -b humble https://github.com/gazebosim/ros_gz.git 

USER root
WORKDIR /home/ros2/ws
RUN rosdep install -r --from-paths src -i -y --rosdistro humble

RUN echo "source /opt/ros/humble/setup.bash" >> /home/ros2/.bashrc
WORKDIR /home/ros2/ws
RUN bash -c "source /opt/ros/humble/setup.bash && colcon build"

RUN apt-get install gz-garden -y
USER ros2
RUN echo "source /home/ros2/ws/install/setup.bash" >> /home/ros2/.bashrc
```

**Comment by azeey** [comment] 2023-03-08 22:03
Can you try exporting the Gazebo version (`GZ_VERSION`) per https://github.com/gazebosim/ros_gz/tree/humble#gazebo

**Comment by doppioandante** [comment] 2023-03-08 22:53
> Can you try exporting the Gazebo version (`GZ_VERSION`) per https://github.com/gazebosim/ros_gz/tree/humble#gazebo

Wow thanks, I had missed that. It seems to be working now, at least the basic chatter message.

As a side note, rosdep doesn't seem so good at finding all the dependencies, I had to install some dev packages manually, but I'm very new to the whole ROS ecosystem so there may be something missing.

I haven't cleaned this up yet, but I guess it could be useful for someone:
```Dockerfile
FROM osrf/ros:humble-desktop

RUN apt-get update
RUN apt-get install kakoune wget gnupg apt-utils -y
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update

RUN apt-get install gz-sim7-cli libgz-transport12-dev libgz-math7-dev libgz-cmake3-dev libignition-cmake2-dev libgz-sim7-dev -y

RUN useradd --create-home --shell /bin/bash ros2

USER ros2
WORKDIR /home/ros2
RUN rosdep update
RUN mkdir -p /home/ros2/ws/src/
RUN cd /home/ros2/ws/src/ && git clone --depth 1 -b humble https://github.com/gazebosim/ros_gz.git 

USER root
WORKDIR /home/ros2/ws
ENV GZ_VERSION=garden
RUN rosdep install -r --from-paths src -i -y --rosdistro humble

RUN echo "source /opt/ros/humble/setup.bash" >> /home/ros2/.bashrc
WORKDIR /home/ros2/ws
RUN bash -c "source /opt/ros/humble/setup.bash && colcon build"

RUN apt-get install gz-garden -y
USER ros2
RUN echo "source /home/ros2/ws/install/setup.bash" >> /home/ros2/.bashrc
```

I can't make a host gz sim instance talk to the dockerized gz bridge, as was in my original plans, but I guess I'll just go on with using gz sim from inside docker. (Yes I tried sharing the same host network for everything.. didn't work)

**Comment by azeey** [comment] 2023-03-08 22:58
> Wow thanks, I had missed that. It seems to be working now, at least the basic chatter message.

Glad it works! And thanks for the reproducible Dockerfile.

> As a side note, rosdep doesn't seem so good at finding all the dependencies, I had to install some dev packages manually, but I'm very new to the whole ROS ecosystem so there may be something missing.

We need to link this in the readme here, but there are some instructions for `rosdep` issues at https://gazebosim.org/docs/garden/ros_installation

@rows-of-houses can you try my suggestion in https://github.com/gazebosim/ros_gz/issues/365#issuecomment-1460937619

**Comment by tommysmth** [comment] 2023-04-19 13:14
I am having the same problem, using also the humble branch. I get a message output by gazebo but none with the ROS topic which is created. So the bridge is creating the topic without passing messages on to it. I've had the problem for geometry_msgs/msg/PoseArray | gz.msgs.Pose_V and sensor_msgs/NavSatFix | gz.msgs.NavSat where the topics are created, but no messages reach through. It's getting even worse when I'm using tf2_msgs/TFMessage | gz.msgs.Pose_V and gps_msgs/GPSFix | gz.msgs.NavSat instead. For those, I'm not even getting a topic on ROS.

**Comment by azeey** [comment] 2023-05-01 22:10
@tommysmth Have you built `ros_gz` from source using `GZ_VERSION=garden`?

**Comment by azeey** [comment] 2023-05-26 18:22
Closing since the issue was resolved by setting `GZ_VERSION=garden` when compiling `ros_gz`.

**Closed as not planned by azeey** 2023-05-26 18:22 UTC
Labels: bug
