### ISSUE TITLE
How to map services with foxy branch (ROS2 Foxy, Ubuntu 20.04, Ign Citadel)

### ISSUE THREAD

**Issue by Vincenzo-Saffioti** [gazebosim/ros_gz#399] opened 2023-05-24 09:51 UTC
## Desired behavior
I would need to map the services offered by ignition citadel, so that I can call them from ROS2 Foxy

## Alternatives considered
How can the problem be solved? Is an alternative suggested?

**Comment by azeey** [comment] 2023-05-26 18:18
Looks like a duplicate of https://github.com/gazebosim/ros_gz/issues/400

**Closed as not planned by azeey** 2023-05-26 18:18 UTC
Labels: enhancement
