### ISSUE TITLE
Failed to create bridge for geometry_msgs/msg/Pose.

### ISSUE THREAD

**Issue by Rak-r** [gazebosim/ros_gz#389] opened 2023-05-09 14:04 UTC
## Environment
* OS Version: Ubuntu 22.04 
* Source or binary build?
  I previously installed binary and it is still there. Then I installed the source version. For this I have also installed gazebo garden from source as I am  having gazebo 11 installed with ros2 humble.

## Description
* Expected behaviour: 
* Actual behaviour: 

## Steps to reproduce

1. Run any robot in gazebo. 
2. Do gz topic -l and get the pose topic and message
3. Then start the bridge: ros2 run ros_gz_bridge parameter_bridge 
4.

**Comment by azeey** [comment] 2023-05-10 14:56
Can you fill out the expected/actual behaviors and the output you get on the terminal? Also, using `ros_gz_bridge` with Garden and ROS Humble required building `ros_gz` with `GZ_VERSION=garden`. Can you verify that you've set the `GZ_VERSION` environment variable?

**Comment by azeey** [comment] 2023-05-26 18:19
Closing because the issue is incomplete and there hasn't been any activity.

**Closed as not planned by azeey** 2023-05-26 18:19 UTC
Labels: bug
